### ISSUE TITLE
Wheel distribution?

### ISSUE THREAD

**Issue by woodruffw** [Pylons/paginate#20]
Hi there! First of all, thanks for this package.

I'm a transitive user of `paginate` (via `Jinja2`), and I just noticed that the [latest release](https://pypi.org/project/paginate/#files) has only a source distribution (sdist) and not a wheel. This isn't a bug from a correctness perspective, but it does result in suboptimal installation performance (since `pip` and other installers have to kick down to the sdist flow rather than decompressing the wheel into the installation prefix).

So, my request: would it be possible to get a wheel attached to a new or current release for `paginate`? This would offer a decent speedup to a lot of downstream users!

**Comment by edgarrmondragon** [comment]
I similarly have a transitive dependency on `paginate`, but via `mkdocs-material`. Happy to help in any way :)
