### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by h4nN** [Pylons/paginate#6]
I'm getting always the same error tried to running a Pyramid app.
the issue is in:

File "/home/ubuntu12/Projects/setech/env34/lib/python3.4/site-packages/paginate-0.5-py3.4.egg/paginate/__init__.py", line 417, in pager

---
 radius = re.search(r'~(\d+)~', format).group(1)

**Comment by ergo** [comment]
Hi,
Can you show me what is the format string you are using with your pager?

Normally format needs to contain a string like "~X~" where X is the number that sets the radius of pages around the current page.

Can you show me how are you using the `pager()` function?

**Comment by h4nN** [comment]
It works, using the version 0.4.3.

**Comment by ergo** [comment]
Can you show me how are you using the function? Then I will be able to recreate the issue and possibly fix problems with it? Our tests and applications work on both versions.
I just need to see how are you calling the `pager()`.

**Comment by ergo** [comment]
@h4nN I've released 0.5.1 that should fix the issue for you, now it is working with pager strings not containing patters valid for `~(\d+)~`.
